### ISSUE TITLE
Setting OS as UBUNTU_LATEST fails

### ISSUE THREAD

**Issue by patrocinio** [patrocinio/kubernetes-softlayer#29]
It doesn't have python pre-installed

**Comment by sidgoyal** [comment]
I was getting errors with ubuntu,  but it was more SSH related errors,  didn't notice any python,  and by extension,  ansible related errors.  Is that related or something different?

**Comment by patrocinio** [comment]
Hello @sidgoyal I got problems with the fact that apparently the UBUNTU_LATEST image in SoftLayer doesn't have python, so the ansible stuff fails.

This is an effect of the PR you created... The PR enabled the use of other OSes, now we need to test with different ones. I'm focused on Ubuntu, as there is a client interested in using it.

Thanks
