### ISSUE TITLE
Networking/Calico won't start

### ISSUE THREAD

**Issue by bradschauf** [patrocinio/kubernetes-softlayer#40]
Get the error:
Unable to update cni config: No networks found in /etc/cni/net.d

**Comment by bradschauf** [comment]
This hack/fix worked for me. Lots of discussion on this and correct fix in the kubernetes 1.6.1 community.

**FIX on master and nodes**
edit /etc/systemd/system/kubelet.service.d/10-kubeadm.conf 
within the ExecStart line remove '$KUBELET_NETWORK_ARGS'
systemctl daemon-reload 
systemctl restart kubelet.service

**Comment by patrocinio** [comment]
Thank you for finding the fix.
Let's find a (creative) way to incorporate this fix into the ansible code.

**Comment by patrocinio** [comment]
Fixed in the latest code drop.
Thank you!
